name: Sync README.md

on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'

jobs:
  sync:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Copy README.md
        run: |
          cp -f README.md ${{ runner.temp }}/README.md

      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          ref: gh-pages

      - name: Commit README.md
        run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README.md from main"
          git push
